#!/bin/sh /etc/rc.common

START=25
USE_PROCD=1

start_service() {
	reload_service
}

service_triggers() {
	procd_add_reload_trigger "network"
	procd_add_reload_trigger "firewall"
	procd_add_raw_trigger "interface.*" 1000 /etc/init.d/smp-packet-steering reload
}

reload_service() {
	/etc/hotplug.d/net/20-smp-packet-steering
}
